name: main

on: [push]

env:
  OMP_NUM_THREADS: 8

jobs:
  CXX_Debug_fallback_linear_algebra:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: |
          mkdir build && cd build
          cmake -G Ninja -C ../.github/gnu_compiler_flags.cmake \
          -D CMAKE_BUILD_TYPE=Debug \
          ..
      - name: build
        run: cmake --build build
      - name: test
        run: cmake --build build --target test
  CXX_Release_fallback_linear_algebra:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: |
          mkdir build && cd build
          cmake -G Ninja -C ../.github/gnu_compiler_flags.cmake \
          -D CMAKE_BUILD_TYPE=Release \
          ..
      - name: build
        run: cmake --build build
      - name: test
        run: cmake --build build --target test
  CXX_Release_Lapack:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: |
          mkdir build && cd build
          cmake -G Ninja -C ../.github/gnu_compiler_flags.cmake \
          -D CMAKE_BUILD_TYPE=Release \
          -D FALLBACK_LINALG=OFF \
          -D LINK_LIBRARIES="blas;lapack" \
          ..
      - name: build
        run: cmake --build build
      - name: test
        run: cmake --build build --target test
  Fortran_Debug_fallback_linear_algebra:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: |
          mkdir build && cd build
          cmake -G Ninja -C ../.github/gnu_compiler_flags.cmake \
          -D CMAKE_BUILD_TYPE=Debug \
          -D BUILD_CXX_VERSION=OFF \
          -D CAF_LIBRARY=caf_shmem \
          -D TESTS_RUN_PREFIX="env;GFORTRAN_NUM_IMAGES=8" \
          ..
      - name: build
        run: cmake --build build
      - name: test
        run: cmake --build build --target test
  Fortran_Release_fallback_linear_algebra:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: |
          mkdir build && cd build
          cmake -G Ninja -C ../.github/gnu_compiler_flags.cmake \
          -D CMAKE_BUILD_TYPE=Release \
          -D BUILD_CXX_VERSION=OFF \
          -D CAF_LIBRARY=caf_shmem \
          -D TESTS_RUN_PREFIX="env;GFORTRAN_NUM_IMAGES=8" \
          ..
      - name: build
        run: cmake --build build
      - name: test
        run: cmake --build build --target test
  Fortran_Release_Lapack:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: |
          mkdir build && cd build
          cmake -G Ninja -C ../.github/gnu_compiler_flags.cmake \
          -D CMAKE_BUILD_TYPE=Release \
          -D BUILD_CXX_VERSION=OFF \
          -D CAF_LIBRARY=caf_shmem \
          -D TESTS_RUN_PREFIX="env;GFORTRAN_NUM_IMAGES=8" \
          -D LINK_LIBRARIES="blas;lapack" \
          ..
      - name: build
        run: cmake --build build
      - name: test
        run: cmake --build build --target test
